package harrow;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;

import javax.imageio.ImageIO;
import harrow.HarrowCard.Alignment;
import harrow.HarrowCard.Suit;

public class HarrowDeck {
	
	private static HarrowDeck hd;
	
	private static HarrowCard[] deck;
	private static ArrayList<HarrowCard> draws;
	
	private HarrowDeck(){
		initialize();
		draws = new ArrayList<>();
	}
	
	public static HarrowDeck getDeck() {
		if (hd==null){
			hd = new HarrowDeck();
		}
		return hd;
	}
	
	private static void initialize() {
		deck = new HarrowCard[54];
		
		deck[0] = new HarrowCard("The Marriage","2C", Alignment.LN,"This is the lawful neutral card of charisma. It represents a union of peoples, ideas, or kingdoms that might be as productive or as ruinous as the bonding of a salamander and a water weird.",Suit.crown,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Strength, Dexterity, Charisma.	Give 2/3 of the tokens on this card to the Strength card. Give the rest to the Dexterity card.	Give 2/3 of the tokens on this card to the Charisma card. Give the rest to the Wisdom card.	Read as if the card in the mind location was the nurture card.	Give 2 tokens to the ability card 3 cards away clockwise.");
		deck[1] = new HarrowCard("The Queen Mother","3C", Alignment.LN,"This is the lawful neutral card of wisdom. This formian is the personification of knowledge, who is fond of the powerless, the underclass, and those who will show her obeisance.",Suit.star,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Strength, Wisdom, Charisma.	Give 2/3 of the tokens on this card to the Strength card. Give the rest to the Constitution card.	Give 2/3 of the tokens on this card to the Wisdom card. Give the rest to the Charisma card.	Read as if the card in the mind location was the nurture card.	Give 1 token to every ability card that is a Hammer, Key, or Shield.");
		deck[2] = new HarrowCard("The Inquisitor","4C", Alignment.LN,"This is the lawful neutral card of intelligence. It represents an immutable object that cannot be deceived or influenced.",Suit.tome,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Constitution, Intelligence, Wisdom.	Give 2/3 of the tokens on this card to the Constitution card. Give the rest to the Strength card.	Give 2/3 of the tokens on this card to the Intelligence card. Give the rest to the Wisdom card.	Read as if the card in the mind location was the nurture card.	Steal 2 tokens from the ability card 1 card away clockwise.");
		deck[3] = new HarrowCard("The Brass Dwarf","5C", Alignment.LN,"This is the lawful neutral card of constitution, showing an azer. It represents a creature invulnerable to a current threat.",Suit.shield,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Strength, Constitution, Wisdom.	Give 2/3 of the tokens on this card to the Constitution card. Give the rest to the Strength card.	Give 2/3 of the tokens on this card to the Wisdom card. Give the rest to the Intelligence card.	Read as if the card in the body location was the nurture card.	Steal 1 token from the card 1 card away clockwise.");
		deck[4] = new HarrowCard("The Locksmith","6C", Alignment.LN,"This is the lawful neutral card of dexterity. It represents the keys the subject needs to unlock his fate. The card grants the tools needed to unlock some new place, puzzle, or hoard.",Suit.key,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Dexterity, Constitution, Wisdom	Give 2/3 of the tokens on this card to the Dexterity card. Give the rest to the Constitution card.	Give 2/3 of the tokens on this card to the Wisdom card. Give the rest to the Intelligence card.	Read as if the card in the body location was the nurture card.	Steal 1 token from the ability card 4 cards away clockwise.");
		deck[5] = new HarrowCard("The Forge","7C", Alignment.LN,"This is the lawful neutral card of strength. It represents strength through diversity, or strength from many sources united against a single trial.",Suit.hammer,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Strength, Wisdom, Charisma.	Give 2/3 of the tokens on this card to the Strength card. Give the rest to the Constitution card.	Give 2/3 of the tokens on this card to the Wisdom card. Give the rest to the Charisma card.	Read as if the card in the body location was the nurture card.	Give 1 token to every ability card that is a Hammer, Key, or Shield.");
		deck[6] = new HarrowCard("The Tyrant","8C", Alignment.LE,"This is the lawful evil card of charisma. It represents a ruler who harms those he rules.",Suit.crown,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Strength, Constitution, Charisma.	Give 2/3 of the tokens on this card to the Strength card. Give the rest to the Constitution card.	Give all of the tokens on this card to the Charisma card.	Charisma.	Steal 1 token from every ability card that is a Hammer, Key, or Shield.");
		deck[7] = new HarrowCard("The Eclipse","9C", Alignment.LE,"This is the lawful evil card of wisdom. It represents loss of faith and purpose, and the subject's doubt about his abilities or prospects.",Suit.star,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Constitution, Intelligence, Wisdom.	Give 2/3 of the tokens on this card to the Constitution card. Give the rest to the Strength card.	Give all of the tokens on this card to the Wisdom card.	Wisdom.	Steal 1 token from the ability card 4 cards away clockwise.");
		deck[8] = new HarrowCard("The Rakshasa","1C", Alignment.LE,"This is the lawful evil card of intelligence. The rakshasa represents domination, mental control, and slavery.",Suit.tome,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Strength, Intelligence, Charisma.	Give 2/3 of the tokens on this card to the Strength card. Give the rest to the Constitution card.	Give all of the tokens on this card to the Intelligence card.	Intelligence.	Steal 2 tokens from the ability card 3 cards away clockwise.");
		deck[9] = new HarrowCard("The Teamster","AC", Alignment.NN,"This is the neutral card of constitution. It represents an external force that drives the subject on.",Suit.shield,null,"Give 3 tokens to each of the body, mind, and Constitution cards.	Dexterity, Constitution, Wisdom	Give 2/3 of the tokens on this card to the Constitution card. Give the rest to the Dexterity card.	Give 2/3 of the tokens on this card to the Charisma card. Give the rest to the Intelligence card.	Constitution	Give 2 tokens to the card 1 card away clockwise.");
		deck[10] = new HarrowCard("The Tangled Briar","JC", Alignment.LE,"This is the lawful evil card of constitution. It represents a historical thing or creature that will have some influence on the question.",Suit.shield,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Dexterity, Constitution, Intelligence.	Give all of the tokens on this card to the Constitution card.	Give 2/3 of the tokens on this card to the Intelligence card. Give the rest to the Wisdom card.	Constitution.	Steal 2 tokens from the card 2 cards away clockwise.");
		deck[11] = new HarrowCard("The Fiend","KC", Alignment.LE,"This is the lawful evil card of strength. It is a devil who devours the masses of the innocent, and can represent the deaths of many in a disaster. ",Suit.hammer,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Strength, Constitution, Intelligence.	Give all of the tokens on this card to the Strength card.	Give 2/3 of the tokens on this card to the Intelligence card. Give the rest to the Charisma card.	Strength.	Steal 1 token from every ability card that is a Hammer, Key, or Shield.");
		deck[12] = new HarrowCard("The Avalanche","QC", Alignment.LE,"This is the lawful evil card of dexterity. It represents disaster: an unthinking panic and destruction that overruns all.",Suit.key,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Strength, Dexterity, Constitution	Give all of the tokens on this card to the Dexterity card.	Give 2/3 of the tokens on this card to the Intelligence card. Give the rest to the Charisma card.	Dexterity.	Steal 2 tokens from the ability card 5 cards away clockwise.");
		deck[13] = new HarrowCard("The Courtesan","2D", Alignment.CN,"This is the chaotic neutral card of charisma. It represents political intrigue and the superficiality of social niceties.",Suit.crown,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Intelligence, Wisdom, Charisma.	Give 2/3 of the tokens on this card to the Dexterity card. Give the rest to the Strength card.	Give 2/3 of the tokens on this card to the Charisma card. Give the rest to the Intelligence card.	Read as if the card in the spirit location was the nurture card.	Steal 1 token from the ability card 2 cards away clockwise.");
		deck[14] = new HarrowCard("The Carnival","3D", Alignment.CN,"This is the chaotic neutral card of wisdom. It represents illusions and false dreams.",Suit.star,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Dexterity, Wisdom, Charisma.	Give 2/3 of the tokens on this card to the Dexterity card. Give the rest to the Strength card.	Give 2/3 of the tokens on this card to the Wisdom card. Give the rest to the Charisma card.	Read as if the card in the spirit location was the nurture card.	Give 1 token to the ability card 1 card away clockwise.");
		deck[15] = new HarrowCard("The Vision","4D", Alignment.CN,"This is the chaotic neutral card of intelligence. It represents esoteric and arcane knowledge, or madness.",Suit.tome,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Dexterity, Constitution, Intelligence.	Give 2/3 of the tokens on this card to the Constitution card. Give the rest to the Dexterity card.	Give 2/3 of the tokens on this card to the Intelligence card. Give the rest to the Wisdom card.	Read as if the card in the spirit location was the nurture card.	Give 2 tokens to the ability card 2 cards away clockwise.");
		deck[16] = new HarrowCard("The Mountain Man","5D", Alignment.CN,"This is the chaotic neutral card of constitution. This giant represents an encounter with a physical power outside of the subject's control.",Suit.shield,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Strength, Dexterity, Constitution.	Give 2/3 of the tokens on this card to the Constitution card. Give the rest to the Strength card.	Give 2/3 of the tokens on this card to the Charisma card. Give the rest to the Intelligence card.	Read as if the card in the nature location was the nurture card.	Steal 2 tokens from the card 1 card away clockwise.");
		deck[17] = new HarrowCard("The Rabbit Prince","6D", Alignment.CN,"This is the chaotic neutral card of dexterity. It represents the quirky vicissitudes of melee combat. The Rabbit Prince is the personification of the capriciousness of battle, and his broken sword indicates that defeat can come to anyone. The card sometimes represents younger members of royal or noble houses.",Suit.key,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Strength, Dexterity, Charisma.	Give 2/3 of the tokens on this card to the Dexterity card. Give the rest to the Strength card.	Give 2/3 of the tokens on this card to the Charisma card. Give the rest to the Intelligence card.	Read as if the card in the nature location was the nurture card.	Steal 2 tokens from the ability card with the most tokens currently (ignore ties and this card.)");
		deck[18] = new HarrowCard("The Uprising","7D", Alignment.CN,"This is the chaotic neutral card of strength. It represents overwhelming strength that catches the subject up in something much more powerful.",Suit.hammer,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Strength, Dexterity, Charisma.	Give 2/3 of the tokens on this card to the Strength card. Give the rest to the Dexterity card.	Give 2/3 of the tokens on this card to the Charisma card. Give the rest to the Wisdom card.	Read as if the card in the nature location was the nurture card.	Give 2 tokens to the ability card 2 cards away clockwise.");
		deck[19] = new HarrowCard("The Unicorn","8D", Alignment.CG,"This is the chaotic good card of charisma. It represents one who generously offers up that which is sought.",Suit.crown,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Strength, Intelligence, Charisma.	Give 2/3 of the tokens on this card to the Strength card. Give the rest to the Constitution card.	Give all of the tokens on this card to the Charisma card.	Charisma.	Give 1 token to every ability card that is a Tome, Star, or Crown.");
		deck[20] = new HarrowCard("The Publican","9D", Alignment.CG,"This is the chaotic good card of wisdom. It represents fellowship and refuge. The cyclops is a seemingly inconsequential figure who nonetheless has relevant insight.",Suit.star,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Strength, Constitution, Wisdom.	Give 2/3 of the tokens on this card to the Constitution card. Give the rest to the Strength card.	Give all of the tokens on this card to the Wisdom card.	Wisdom.	Give 1 token to the ability card 3 cards away clockwise.");
		deck[21] = new HarrowCard("The Joke","1D", Alignment.CG,"This is the chaotic good card of intelligence. It represents a monster that can only be defeated through trickery, or the value of humor in circumventing difficult people.",Suit.tome,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Dexterity, Intelligence, Charisma.	Give 2/3 of the tokens on this card to the Dexterity card. Give the rest to the Constitution card.	Give all of the tokens on this card to the Intelligence card.	Intelligence.	Give 1 token to the ability card 4 cards away clockwise.");
		deck[22] = new HarrowCard("The Peacock","AD", Alignment.NN,"This is the neutral card of dexterity. It represents a great beauty that can only be preserved if petrified and frozen in time for eternity, as by a cockatrice's glare.",Suit.key,null,"Give 3 tokens to each of the body, mind, and Dexterity cards.	Dexterity, Intelligence, Charisma.	Give 2/3 of the tokens on this card to the Dexterity card. Give the rest to the Constitution card.	Give 2/3 of the tokens on this card to the Charisma card. Give the rest to the Intelligence card.	Dexterity.	Steal 2 tokens from the ability card 4 cards away clockwise.");
		deck[23] = new HarrowCard("The Desert","JD", Alignment.CG,"This is the chaotic good card of constitution. It represents an environment too difficult for anyone to survive without help. The sphinx may represent a source of salvation from plague.",Suit.shield,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Constitution, Wisdom, Charisma.	Give all of the tokens on this card to the Constitution card.	Give 2/3 of the tokens on this card to the Wisdom card. Give the rest to the Charisma card.	Constitution.	Give 1 token to the ability card 5 cards away clockwise.");
		deck[24] = new HarrowCard("The Big Sky","KD", Alignment.CG,"This is the chaotic good card of strength. It represents momentous change, as when all the slaves of a nation are emancipated.",Suit.hammer,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Strength, Dexterity, Wisdom.	Give all of the tokens on this card to the Strength card.	Give 2/3 of the tokens on this card to the Wisdom card. Give the rest to the Intelligence card.	Strength.	Give 1 token to every other ability card.");
		deck[25] = new HarrowCard("The Juggler","QD", Alignment.CG,"This is the chaotic good card of dexterity. It represents destiny, deities, and those who play with the fates of others.",Suit.key,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Dexterity, Wisdom, Charisma.	Give all of the tokens on this card to the Dexterity card.	Give 2/3 of the tokens on this card to the Charisma card. Give the rest to the Wisdom card.	Dexterity.	Give 1 token to the ability card 3 cards away clockwise.");
		deck[26] = new HarrowCard("The Theater","2H", Alignment.NG,"This is the neutral good card of charisma. It represents prophecy, with a true prophet acting a part as the puppet of the gods.",Suit.crown,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Constitution, Wisdom, Charisma.	Give 1/3 of the tokens on this card to each of the Strength, Dexterity, and Constitution cards.	Give 1/3 of the tokens on this card to each of the Intelligence, Wisdom, and Charisma cards.	Charisma.	Give 2 tokens to the ability card 4 cards away clockwise.");
		deck[27] = new HarrowCard("The Midwife","3H", Alignment.NG,"This is the neutral good card of wisdom. It represents the enabler or conduit of new creation, information, or arrivals.",Suit.star,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Constitution, Wisdom, Charisma.	Give 1/3 of the tokens on this card to each of the Strength, Dexterity, and Constitution cards.	Give 1/3 of the tokens on this card to each of the Intelligence, Wisdom, and Charisma cards.	Wisdom.	Give 2 tokens to the ability card 1 card away clockwise.");
		deck[28] = new HarrowCard("The Wanderer","4H", Alignment.NG,"This is the neutral good card of intelligence. It represents a centaur collector who appreciates things others discard as junk.",Suit.tome,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Strength, Dexterity, Intelligence.	Give 1/3 of the tokens on this card to each of the Strength, Dexterity, and Constitution cards.	Give 1/3 of the tokens on this card to each of the Intelligence, Wisdom, and Charisma cards.	Intelligence.	Give 1 token to the ability card 2 cards away clockwise.");
		deck[29] = new HarrowCard("The Survivor","5H", Alignment.NG,"This is the neutral good card of constitution. It represents a creature that has managed to survive a terrible ordeal, when everyone thought him lost.",Suit.shield,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Strength, Constitution, Intelligence.	Give 1/3 of the tokens on this card to each of the Strength, Dexterity, and Constitution cards.	Give 1/3 of the tokens on this card to each of the Intelligence, Wisdom, and Charisma cards.	Constitution.	Give 1 token to the ability card 1 card away clockwise.");
		deck[30] = new HarrowCard("The Cricket","6H", Alignment.NG,"This is the neutral good card of dexterity. It represents the grig, quick travel, and the reward at the end of a journey.",Suit.key,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Dexterity, Constitution, Wisdom.	Give 1/3 of the tokens on this card to each of the Strength, Dexterity, and Constitution cards.	Give 1/3 of the tokens on this card to each of the Intelligence, Wisdom, and Charisma cards.	Dexterity.	Give 1 token to every ability card that is a Tome, Star, or Crown.");
		deck[31] = new HarrowCard("The Keep","7H", Alignment.NG,"This is the neutral good card of strength. It represents quiet, unshakeable strength that withstands any hardship.",Suit.hammer,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Strength, Constitution, Wisdom	Give 1/3 of the tokens on this card to each of the Strength, Dexterity, and Constitution cards.	Give 1/3 of the tokens on this card to each of the Intelligence, Wisdom, and Charisma cards.	Strength.	Give 1 token to the ability card 2 cards away clockwise.");
		deck[32] = new HarrowCard("The Empty Throne","8H", Alignment.LG,"This is the lawful good card of charisma. It represents those who are gone, or a ghost of the past that has taught important lessons.",Suit.crown,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Strength, Wisdom, Charisma.	Give 2/3 of the tokens on this card to the Strength card. Give the rest to the Dexterity card.	Give all of the tokens on this card to the Charisma card.	Charisma.	Give 2 tokens to the ability card with the fewest tokens currently (ignore ties and this card.)    ");
		deck[33] = new HarrowCard("The Winged Serpent","9H", Alignment.LG,"This is the lawful good card of wisdom. It represents the couatl, the bridge of understanding between the towers of knowledge and judgement.",Suit.star,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Strength, Intelligence, Wisdom.	Give 2/3 of the tokens on this card to the Strength card. Give the rest to the Dexterity card.	Give all of the tokens on this card to the Wisdom card.	Wisdom.	Give 2 tokens to the ability card 5 cards away clockwise.");
		deck[34] = new HarrowCard("The Hidden Truth","1H", Alignment.LG,"This is the lawful good card of intelligence. It represents the discovery of the greater truth within.",Suit.tome,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Intelligence, Wisdom, Charisma.	Give 2/3 of the tokens on this card to the Constitution card. Give the rest to the Strength card.	Give all of the tokens on this card to the Intelligence card.	Intelligence.	Give 2 tokens to the ability card with the most tokens currently (ignore ties and this card.)");
		deck[35] = new HarrowCard("The Bear","AH", Alignment.NN,"This is the neutral card of strength. It represents pure strength that cannot be truly tamed or trained.",Suit.hammer,null,"Give 3 tokens to each of the body, mind, and Strength cards.	Strength, Dexterity, Constitution.	Give 2/3 of the tokens on this card to the Strength card. Give the rest to the Constitution card.	Give 2/3 of the tokens on this card to the Wisdom card. Give the rest to the Charisma card.	Strength.	Give 1 token to the ability card 4 cards away clockwise.");
		deck[36] = new HarrowCard("The Trumpet","JH", Alignment.LG,"This is the lawful good card of constitution. It represents an archon who dives aggressively and righteously into danger.",Suit.shield,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Strength, Constitution, Charisma.	Give all of the tokens on this card to the Constitution card.	Give 2/3 of the tokens on this card to the Charisma card. Give the rest to the Wisdom card.	Constitution.	Give 2 tokens to the ability card 3 cards away clockwise.");
		deck[37] = new HarrowCard("The Paladin","KH", Alignment.LG,"This is the lawful good card of strength. It represents standing resolutely against trouble, without backing down.",Suit.hammer,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Strength, Constitution, Charisma	Give all of the tokens on this card to the Strength card.	Give 2/3 of the tokens on this card to the Charisma card. Give the rest to the Wisdom card.	Strength.	Give 2 tokens to the ability card 5 cards away clockwise.");
		deck[38] = new HarrowCard("The Dance","QH", Alignment.LG,"This is the lawful good card of dexterity. It represents a complicated framework that requires the cooperation of all to avoid collapse.",Suit.key,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Strength, Dexterity, Wisdom.	Give all of the tokens on this card to the Dexterity card.	Give 2/3 of the tokens on this card to the Wisdom card. Give the rest to the Charisma card.	Dexterity.	Give 2 tokens to the ability card 4 cards away clockwise.");
		deck[39] = new HarrowCard("The Betrayal","2S", Alignment.NE,"This is the neutral evil card of charisma. It represents selfishness and envy.",Suit.crown,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Strength, Dexterity, Intelligence.	Give 2/3 of the tokens on this card to the Strength card. Give the rest to the Dexterity card.	Give 2/3 of the tokens on this card to the Charisma card. Give the rest to the Wisdom card.	Charisma.	Steal 2 tokens from the ability card 4 cards away clockwise.");
		deck[40] = new HarrowCard("The Mute Hag","3S", Alignment.NE,"This is the neutral evil card of wisdom. It represents the insightful hag, a purveyor of blood pacts, treacherous secrets, and discord.",Suit.star,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Constitution, Intelligence, Charisma.	Give 2/3 of the tokens on this card to the Constitution card. Give the rest to the Dexterity card.	Give 2/3 of the tokens on this card to the Wisdom card. Give the rest to the Charisma card.	Wisdom.	Steal 1 token from every ability card that is a Tome, Star, or Crown.");
		deck[41] = new HarrowCard("The Idiot","4S", Alignment.NE,"This is the neutral evil card of intelligence. It represents folly, greed, blackmail, bribery, or hubris.",Suit.tome,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Dexterity, Constitution, Charisma.	Give 2/3 of the tokens on this card to the Dexterity card. Give the rest to the Constitution card.	Give 2/3 of the tokens on this card to the Intelligence card. Give the rest to the Charisma card.	Intelligence.	Steal 1 token from the ability card 1 card away clockwise.");
		deck[42] = new HarrowCard("The Sickness","5S", Alignment.NE,"This is the neutral evil card of constitution. It represents corruption, famine, plague, pestilence, and disease.",Suit.shield,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Dexterity, Intelligence, Wisdom.	Give 2/3 of the tokens on this card to the Constitution card. Give the rest to the Dexterity card.	Give 2/3 of the tokens on this card to the Intelligence card. Give the rest to the Wisdom card.	Constitution.	Steal 1 token from the card 5 cards away clockwise.");
		deck[43] = new HarrowCard("The Crows","6S", Alignment.NE,"This is the neutral evil card of dexterity. It represents murder, theft, and the violent loss of that which is loved.",Suit.key,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Strength, Intelligence, Wisdom.	Give 2/3 of the tokens on this card to the Dexterity card. Give the rest to the Strength card.	Give 2/3 of the tokens on this card to the Intelligence card. Give the rest to the Wisdom card.	Dexterity.	Steal 1 token from every other ability card.");
		deck[44] = new HarrowCard("The Beating","7S", Alignment.NE,"This is the neutral evil card of strength. It represents an assault from all quarters, or the mental dissolution of the self.",Suit.hammer,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Dexterity, Constitution, Wisdom	Give 2/3 of the tokens on this card to the Strength card. Give the rest to the Dexterity card.	Give 2/3 of the tokens on this card to the Wisdom card. Give the rest to the Intelligence card.	Strength.	Steal 1 token from the ability card 3 cards away clockwise.");
		deck[45] = new HarrowCard("The Liar","8S", Alignment.CE,"This is the chaotic evil card of charisma. It represents destructive, treacherous love. The lamia signals obsession, star-crossed lovers, or unrequited desire.",Suit.crown,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Dexterity, Intelligence, Charisma.	Give 2/3 of the tokens on this card to the Dexterity card. Give the rest to the Constitution card.	Give all of the tokens on this card to the Charisma card.	Charisma.	Steal 1 token from the ability card 3 cards away clockwise.");
		deck[46] = new HarrowCard("The Lost","9S", Alignment.CE,"This is the chaotic evil card of wisdom. The bodak represents the permanently insane, lost among lunatics and psychopaths in insane asylums. It is a card of emptiness.",Suit.star,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Dexterity, Intelligence, Wisdom.	Give 2/3 of the tokens on this card to the Dexterity card. Give the rest to the Strength card.	Give all of the tokens on this card to the Wisdom card.	Wisdom.	Steal 2 tokens from the ability card 5 cards away clockwise.");
		deck[47] = new HarrowCard("The Snakebite","1S", Alignment.CE,"This is the chaotic evil card of intelligence. It represents poison, venom, assassination, and discord.",Suit.tome,null,"Give 6 tokens to the mind card and 3 tokens to the body card.	Dexterity, Constitution, Intelligence.	Give 2/3 of the tokens on this card to the Constitution card. Give the rest to the Dexterity card.	Give all of the tokens on this card to the Intelligence card.	Intelligence.	Steal 1 token from the ability card 5 cards away clockwise.");
		deck[48] = new HarrowCard("The Foreign Trader","AS", Alignment.NN,"This is the neutral card of intelligence. It represents spies, merchants, and those who trade in information.",Suit.tome,null,"Give 3 tokens to each of the body, mind, and Intelligence cards.	Constitution, Intelligence, Wisdom.	Give 2/3 of the tokens on this card to the Constitution card. Give the rest to the Dexterity card.	Give 2/3 of the tokens on this card to the Intelligence card. Give the rest to the Charisma card.	Intelligence.	Give 1 token to the ability card 5 cards away clockwise.");
		deck[49] = new HarrowCard("The Waxworks","JS", Alignment.CE,"This is the chaotic evil card of constitution. It represents a place of torture, imprisonment, helplessness, and paralysis.",Suit.shield,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Constitution, Intelligence, Wisdom.	Give all of the tokens on this card to the Constitution card.	Give 2/3 of the tokens on this card to the Intelligence card. Give the rest to the Wisdom card.	Constitution.	Steal 1 token from every ability card that is a Tome, Star, or Crown.");
		deck[50] = new HarrowCard("The Cyclone","KS", Alignment.CE,"This is the chaotic evil card of strength. It represents an unstoppable, destructive force unleashed through the plots of intelligent creatures.",Suit.hammer,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Strength, Constitution, Intelligence.	Give all of the tokens on this card to the Strength card.	Give 2/3 of the tokens on this card to the Intelligence card. Give the rest to the Charisma card.	Strength.	Steal 2 tokens from the ability card 3 cards away clockwise.");
		deck[51] = new HarrowCard("The Demon's Lantern","QS", Alignment.CE,"This is the chaotic evil card of dexterity. It represents an impossible situation of traps, mind tricks, and sleight of hand.",Suit.key,null,"Give 6 tokens to the body card and 3 tokens to the mind card.	Strength, Dexterity, Intelligence.	Give all of the tokens on this card to the Dexterity card.	Give 2/3 of the tokens on this card to the Intelligence card. Give the rest to the Charisma card.	Dexterity.	Steal 1 token from the ability card 2 cards away clockwise.");
		deck[52] = new HarrowCard("The Twin","J", Alignment.NN,"This is the neutral card of charisma. The doppelganger represents duality of purpose or identity, or indecision and fence-sitting for the subject or the entire spread.",Suit.crown,null,"Give 3 tokens to each of the body, mind, and Charisma cards.	Dexterity, Constitution, Charisma.	Give 2/3 of the tokens on this card to the Dexterity card. Give the rest to the Constitution card.	Give 2/3 of the tokens on this card to the Charisma card. Give the rest to the Intelligence card.	Charisma.	Steal 2 tokens from the ability card 2 cards away clockwise.");
		deck[53] = new HarrowCard("The Owl","J", Alignment.NN,"This is the neutral card of wisdom. It represents the harsh wisdom of the natural order. The owl holds a needle that can bind life together or pick it apart.",Suit.star,null,"Give 3 tokens to each of the body, mind, and Wisdom cards.	Intelligence, Wisdom, Charisma.	Give 2/3 of the tokens on this card to the Dexterity card. Give the rest to the Strength card.	Give 2/3 of the tokens on this card to the Wisdom card. Give the rest to the Intelligence card.	Wisdom.	Steal 2 tokens from the ability card with the fewest tokens currently (ignore ties and this card.)    ");

		
//		deck[0] = new HarrowCard("The Avalanche", "QC", Alignment.LE, "This is the lawful evil card of dexterity. It represents disaster: an unthinking panic and destruction that overruns all.", Suit.key, null, null);
//		deck[0].setImage(loadImage(deck[0].name()+".jpg"));
		for (int i = 0; i < deck.length; i++) {
			deck[i].setImage(loadImage("images/"+deck[i].name()));
			
		}
	}
	
	private static BufferedImage loadImage(String name) {
		try {
			File f = new File(name+".jpg");
			if(!f.exists()) {
				f = new File(name+".png");
				if(!f.exists()) 
					throw new IOException("File "+name+" does not exist. Using default.");
				else name += ".png";
			}else name += ".jpg";
			return ImageIO.read(new File(name));
		} catch (IOException e) {
			if ((new File(name+".jpg")).exists()||(new File(name+".png")).exists())
				e.printStackTrace();
			else
				System.err.println("Couldn't find image file: "+name);
			BufferedImage bi = new BufferedImage(100, 100, BufferedImage.TYPE_INT_ARGB);
			Graphics2D g = (Graphics2D)bi.getGraphics();
			g.setBackground(Color.BLACK);
			g.setColor(Color.BLACK);
			g.fillRect(0, 0, 100, 100);
			g.setColor(Color.white);
			g.drawChars(name.substring(0, name.length()-4).toCharArray(), 0, name.length()-4, 0, 50);
			return bi;
		}
	}
	
	private static BufferedImage blank;
	
	protected static BufferedImage getDefaultImage() {
		if(blank==null) {
			blank = new BufferedImage(100, 100, BufferedImage.TYPE_INT_ARGB);
			Graphics2D g = (Graphics2D)blank.getGraphics();
			g.setColor(Color.black);
			g.fillRect(0, 0, 100, 100);
		}
		return blank;
	}
	
	public void shuffle() {
		draws.clear();
		draws.addAll(Arrays.asList(deck));
		Collections.shuffle(draws);
	}
	
	public HarrowCard draw() {
		if (draws.isEmpty())
			return null;
		return draws.remove(0);
	}
	
}
